# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    - task: check

  build:
    - "{{.RUN}} src/auto-spacing.py {{.GEN}} {{.CLI_ARGS}} > auto-spacing.txt"

  check:
    - task: type
    - task: lint
    - task: fmtchk

  fix: "{{.RUN}} ruff check --fix {{.CLI_ARGS}}"
  fmt: "{{.RUN}} ruff format {{.CLI_ARGS}}"
  fmtchk: "{{.RUN}} ruff format --check {{.CLI_ARGS}}"
  lint: "{{.RUN}} ruff check {{.CLI_ARGS}}"
  type: "{{.RUN}} pyrefly check {{.PYREFLY}} {{.CLI_ARGS}}"

vars:
  GEN:
  PYREFLY: --summarize-errors
  RUN: uv run
