# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    - task: check

  build:
    - "{{.RUN}} src/auto-spacing.py {{.GEN}} {{.CLI_ARGS}} > auto-spacing.txt"

  check:
    - "{{.RUN}} yapf -ir -vv src"
    - task: type

  type: "{{.RUN}} pyrefly check {{.PYREFLY}} {{.CLI_ARGS}}"

vars:
  GEN:
  PYREFLY: --summarize-errors
  RUN: uv run
